@baseUrl = http://localhost:3000


###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ 
    "username": "admin",
    "password": "admin"
}

###
@authToken = {{login.response.body.token}}
###

### 
# @name place-buy-order
POST {{baseUrl}}/order/buy
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "orderType": "buy",
    "price": 20,
    "amount": 10,
    "currencySrcSym": "USD",
    "currencyDestSym": "DOGE"
}

### 
# @name place-sell-order
POST {{baseUrl}}/order/sell
Content-Type: application/json
Authorization: Bearer {{authToken}}

{      
    "orderType": "sell",
    "price": 20,
    "amount": 10000,
    "currencySrcSym": "THB",
    "currencyDestSym": "BTC"
}

### 
# @name cancel-order
POST {{baseUrl}}/order/cancel-order
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "orderId": 4
}


###
# @name get-orders
GET {{baseUrl}}/order/search?
Authorization: Bearer {{authToken}}

###
# @name get-order-filter
GET {{baseUrl}}/order/search?orderType=buy&src=USD&dest=BTC&status=cancelled
Authorization: Bearer {{authToken}}

###
# @name get-order-by-status
GET {{baseUrl}}/order/search?status=cancelled
Authorization: Bearer {{authToken}}
